#include "Global.h"

extern char const* cascade_name;
extern char const* colorClassifierPathName;
extern char const* glossModelPathName;
extern char const* cascade_nameL;
extern char const* colorClassifierPathNameZ;
CvScalar efscf();
void faii(IplImage* imageSrc1);
IplImage* gfsi();
CvScalar elcf();
CvRect gfrt();
CvRect lpal(IplImage* faceDown_Gray,bool &falg_Lip,CvRect lip_region);
int llrf(IplImage* image_lip);
IplImage* gtli();
int lpdt(IplImage* faceDown_Gray);
void bcmm();
void ccpm();
bool dtlr(IplImage*& image_LipBi,CvRect& rect_Lip);
void fsdmm(IplImage* src,const int haarFaceDetectSwitch);
void dysal(const IplImage* inputImage);
int copdt(const CvScalar skinColor);
CvScalar glopt(IplImage* inputImage);
void lsgi(const IplImage* face);
bool prodp();
IplImage* gtlm();
void opmm(const IplImage* image_LipBi,const CvRect rect_Lip);
void lcet(const int maxStep);
void fllc(IplImage* contour);
void sglp();
int cptz(const CvScalar lipColor);
void bbmm();
void ccpp();
void cdbt(const IplImage* mask,const IplImage* grayImage,int& i_dark,int& i_bright,double rate_dark,double rate_bright);
void itds();
void cadbt(const IplImage* mask,const IplImage* grayImage,int& i_dark,int& i_bright,double rate_dark,double rate_bright,float lowPart);
void dysz(const IplImage* inputImage);
void ilmf(IplImage* mask);
IplImage* fipa(IplImage* mask,int step);
IplImage* gefit();
bool detect();
CvRect lple(IplImage* faceDown_Gray,bool &falg_Lip);
bool fsdbmpf();
void ldi(IplImage* imageSrc1);
bool detectLip();
CvRect gtrl();
void lipFenGe(IplImage*& image_LipBi, CvRect rect_Lip);