#include "Global.h"
void tdi(IplImage* imageSrc1);
bool dddss();
void ttssii(IplImage* in,int haarTonguedddsswitch=0);
bool ppff();
IplImage* gtmm();
IplImage* gtii();
IplImage* gtim();
void dyss();
void cgii();
void cgee();
bool ftcc();
void cftt(IplImage* image,IplImage*imageResult,CvPoint point_top,CvPoint point_down);
void ctmm();
void sgtt();
bool ccmm();
void dtmc(IplImage* &image_TongueContour1,CvRect &tongueRect1);
void ggff(IplImage* I1,IplImage* p1,int r1,double eps1);
void caqq();
IplImage* ggqq();
void nmlz(IplImage* src,IplImage* dst);
void rghcu(IplImage* src);
void cnbp(int x0,int y0);
void carh();
IplImage* girh();
void ddkk(IplImage* src);
void cadk();
IplImage* gdib();
void wwfff(IplImage* giudedFilterImage,IplImage* imageRoughness);
void catt();
void cagg(); 
void calll();  
void pwff(int x,int y); 
void psfw();
IplImage* ggll();
int tcdd(IplImage* inputImage);
void tftd();
int prdt(IplImage *tongueMask);
float power(float a, int n);
int LSF(vector<CvPoint2D64f> vec, int index_power);
IplImage* ddccyy(IplImage* in, double lowThresh, double highThresh,double aperture);
int ttpt(float data[]);
IplImage * fdrt(IplImage * image);
void tcns(IplImage* tongueImage1,IplImage* tongueMask1);
void pffl();
IplImage* gtci();
IplImage* gtni();
IplImage* tbre(IplImage* in,IplImage* mask);
void cicbm(const IplImage* imageSrc, IplImage* imageResult,int cluster_count);
void tose(IplImage* imageSrc,IplImage* imageResult,IplImage* tongueCoat,IplImage* tongueNature);
void tctd(IplImage* tongueCoatImage1,IplImage* tongueNatureImage1);
int prbh();
void exfe();
CvScalar tofe(IplImage* image);
int cohi(IplImage *src);
float tcdr(IplImage* tongueCoat,IplImage* tongueNature,CvScalar tongueCoatFeature,CvScalar tongueNatureFeature,CvRect coatRect);
int colorhist5(IplImage *src);
vector<int> canshu(IplImage *in);
CvScalar tsbd(IplImage *in,int &substanceResponse);
void tccr(const IplImage* tongueCoatImage1);
CvScalar etccf();
int ccopd(const CvScalar coatColor);

extern char const* cascade_nameS;
extern char const* ccolorClassifierPathName;
extern char const* bohouClassifierPathName;
extern char const* panClassifierPathName;

